### ISSUE TITLE
Fedora 37 ansible docker image

### ISSUE THREAD

**Issue by stefangweichinger** [geerlingguy/docker-fedora36-ansible#1]
Unsure where to file this issue:  I hope you will release a Fedora-37-image as soon as Fedora 37 will be released ;-)
I am preparing tests already and running the beta, so I am looking forward to that docker image. Thanks for your work!

**Comment by geerlingguy** [comment]
Check out new repo, where there's an issue for the problem of the container not running in the background appropriately: https://github.com/geerlingguy/docker-fedora37-ansible/issues/1
